config/routes.rb
Beautytube::Application.routes.draw do

	root to: 'videos#index'

  get '/videos/:query', to: 'videos#show', as: 'video'
end

app/models/video.rb
class Video < ActiveRecord::Base
  # attr_accessible :title, :body
  require 'httparty'

	include HTTParty
	base_uri 'https://gdata.youtube.com'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def show
    @query = params[:query]
    @randnumber = rand(0...10)
    @page = rand(0...100)
    @results = Video.get('/feeds/api/videos?&max-results=10&start-index='+ "#{@page}", :query => {:q => @query, :alt => 'json', :viewCount => 'rating'})
    @first_url = @results["feed"]["entry"][@randnumber]["id"]["$t"]
    @video_title = @results["feed"]["entry"][@randnumber]["title"]["$t"]
    # @first_url_long = @results["feed"]["link"][3]["href"]
    # @second_url_long = @results["feed"]["link"][4]["href"]

    @id = @first_url.split("videos/")[1]
    @url = "https://www.youtube.com/embed/" + @id
  end

  def index
    @braid = "how to hair braids"
    @color = "hair color dye"
    @eye = "eye makeup tutorial"
    @lip = "lip makeup lipstick tutorial"
    @nail = "nail painting tricks"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/video_helper.rb
module VideoHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<script type="text/javascript" src="//use.typekit.net/rxo4wpe.js"></script>
	<script type="text/javascript">try{Typekit.load();}catch(e){}</script>
  <title>Beautytube</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link rel="icon" type="image/png" href="/lipred.png">
</head>
<body>
<div id= "wrap">
<!--   <div class="container"> -->
<!--     <div class="row-fluid">
      <div class="span12"> -->
        <%= render 'nav-bar' %>
         <%= yield %>
        </div>
      </div>
    </div>
  </div>
</div>
</body>
</html>

app/views/videos/_nav-bar.html.erb
<nav class="navbar navbar-default navbar-static-top" role="navigation">
	<div class="container-fluid">
		<div class="navbar-header">
  		<a class="navbar-brand" id="navbar-title" href="#">Beautytube</a>
  	</div><!-- /.navbar-header -->
  	<div class="collapse navbar-collapse" id="navbar-main">
			<ul class="nav navbar-nav navbar-right">
				<li><a id="navbar-title" href="#">About</a></li>
			</ul>
  	</div> <!-- /.navbar-collapse -->
	</div><!-- /.container-fluid -->
</nav>

app/views/videos/index.html.erb
<div class= "container-fluid" id="homepage-container">
  <div class="row" id="hero-header-row">
    <div class="hero"></div>
    <div class="header">
      <div class="col-md-10 col-md-push-2">
        <h3>What will you beautify today?</h3>
      </div>
    </div>
  </div>
  <div class= "row">
    <div class="col-md-2 col-md-offset-1">
      <div class="box" id="hair">
        <ul>Hair</ul>
          <li class ="category-choices" id="braids"><%= link_to "Braids", video_path(@braid) %></li>
          <li class ="category-choices" id="coloring"><%= link_to "Coloring", video_path(@color) %></li>
      </div>
    </div>
    <div class="col-md-2 col-md-offset-2">
      <div class="box" id="face">
        <ul>Face</ul>
          <li class ="category-choices" id="eyes"><%= link_to "Eyes", video_path(@eye) %></li>
          <li class ="category-choices" id="lips"><%= link_to "Lips", video_path(@lip) %></li>
      </div>
    </div>
    <div class="col-md-2 col-md-offset-2">
      <div class="box" id="body">
        <ul>Body</ul>
          <li class ="category-choices" id="nails"><%= link_to "Nails", video_path(@nail) %></li>
      </div>
    </div>
  </div>
</div>

app/views/videos/show.html.erb
<div class= "container-fluid" id="category-container">
  <div class="row">
    <ol class="breadcrumb">
      <li><a href="/">Home</a></li>
      <li class="active" id="category"></li>
    </ol>
  </div>
  <div class= "row">
    <div class="col-sm-7 col-sm-offset-1">
      <h4>Video title:</h4>
      <p><%= @video_title %></p>
<!--       <p><%= @results %></p> -->
    </div>
  </div>
  <div class= "row">
    <div class="col-sm-7 col-sm-offset-1">
      <iframe id="ytplayer" type="text/html" width="640" height="390"
      src=<%= "#{@url}" %> frameborder="0" allowfullscreen>
      </iframe>
    </div>
    <div class="col-sm-2 col-sm-offset-1 next-screen img">
      <a href="javascript:location.reload(true);"><img src="/assets/threenails.png">Next video </a>
    </div>
  </div>
</div>